[package]
name = "polimi-thesis-classical-format"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Alberto Nidasio <https://github.com/NidasioAlberto>"]
license = "MIT"
keywords = ["Politecnico di Milano", "Polytechnic University of Milan", "Polimi"]
description = "Classical Format Thesis for Polytechnic University of Milan."
categories = ["thesis"]

[template]
path = "template"
entrypoint = "main.typ"
# TODO: thumbnail = "thumbnail.png"
